[alembic]
script_location = alembic
prepend_sys_path = .
version_path_separator = os

# Sync URL (Alembic psycopg2 ile çalışır)
sqlalchemy.url = postgresql+psycopg2://xrider:xrider_dev_pass@localhost:5432/xrider
